services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:80
    networks:
      - app_network
  other:
    container_name: other
    build:
      context: .
      dockerfile: ./apps/other/Dockerfile
    restart: always
    ports:
      - 3001:80
    networks:
      - app_network
  ssrweb:
    container_name: ssrweb
    build:
      context: .
      dockerfile: ./apps/ssrweb/Dockerfile
    restart: always
    ports:
      - 3002:3000
    networks:
      - app_network

networks:
  app_network:
